### ISSUE TITLE
Converting large proteins

### ISSUE THREAD

**Issue by wlgfour** [soedinglab/CCMpred#17] opened 2019-08-02 15:11 UTC
Hi,

I am trying to use ccmpred on large MSAs (~12,000 rows and ~3,000 columns). I compiled it with 
padding off as well as no cuda and the system has roughly 750GB of free RAM with more swap available. The calculation that is provided for the memory requirement (4*(4*(L*L*21*21 + L*20) + 23*N*L + N + L*L) + 2*N*L + 1024) tells me that my conversion should only take ~70GB of RAM, but ccmpred exits immediately with an error message "not enough memory to allocate variables."

Thank you for your help!

**Comment by croth1** [comment] 2019-08-05 12:44
Dear @wlgfour, 

I can confirm that there seems to be a problem with very large L.

L=3000 gives 3000x3000x21x21 coupling parameters alone. The number of parameters in CCMpred are encoded as a raw int, therefore limited by 2^31-1. It could be possible to rescue that by changing this to size_t. I am not sure whether the problem will be infeasible due to runtime though.

Unfortunately, we do not have anybody working on CCMpred here, so there is only very limited support available.

**Comment by wlgfour** [comment] 2019-08-06 20:52
Thank you for your timely response!

How would you recommend changing this? Just change all instances of "int" to "size_t"?

With respect to the potential runtime infeasibility, do do you know of any other programs or strategies that might be more practical for large proteins?

**Comment by croth1** [comment] 2019-08-09 07:00
I'd try changing `nvar` to size_t here: https://github.com/soedinglab/CCMpred/blob/master/include/ccmpred.h#L65. Could be that you have to change some followup problems related to the change of data types. 

> With respect to the potential runtime infeasibility, do do you know of any other programs or strategies that might be more practical for large proteins?

I do not know of any coupling based approach that does not have the same runtime limitations as CCMpred.

**Comment by wlgfour** [comment] 2019-08-12 13:08
I am still getting either `ERROR: ERROR: Not enough memory to allocate variables!` or `Segmentation fault (core dumped)` after changing `nvar` to size_t.

**Comment by sokrypton** [comment] 2019-08-12 15:10
We have a slightly slower (non-gpu), implementation that requires only 1/2 the memory (I believe) you can try here: https://github.com/sokrypton/GREMLIN_CPP

**Closed** 2019-09-11 19:57 UTC
